### ISSUE TITLE
화면 전환 시에 어플리케이션이 작동을 멈추는 이슈

### ISSUE THREAD

**Issue by qowngus33** [qowngus33/Pet-Chatbot#1]
intent 객체를 사용하여 로그인 화면과 메인 화면 간의 전환을 수행하려 했으나
로그인 완료 후에 어플리케이션이 작동을 멈추는 오류가 발생하였음

**Comment by eun6** [comment]
메니페스트 파일에 액티비티 정보를 추가함으로 해결함.
